server:
  port: 8080

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false
    healthCheck:
      enabled: true # 开启健康检查
    service-url:
      defaultZone: http://localhost:8080/eureka/
  server:
    enable-self-preservation: false
    # 注册中心清理服务列表间隔
    eviction-interval-timer-in-ms: 10000

spring:
  application:
    name: rigister-center
